[build]
  base = "/"
  command = "npm run build"
  publish = "public"

[context.production.environment]
  NODE_ENV = "production"

[context.branch-deploy]
  command = "npm run build"
  publish = "public"